[lint.per-file-ignores]
"benchmark_suite.py" = ["F821"]
"chat.py" = ["F401", "F841"]
"verify_correctness.py" = ["F541"]
"generate.py" = ["F841"]
"csrc/kernels/__init__.py" = ["F401"]
"csrc/megakernel/__init__.py" = ["F401", "F841"]
"csrc/megakernel/benchmark_prefill.py" = ["E402"]
"csrc/megakernel/test_compare.py" = ["E402"]
"csrc/megakernel/test_prefill.py" = ["E402"]
